window.actionsSrc = [  
   {  
      "id":"shit-economic",
      "title":"Ввести плановую экономику",
      "dpain":8,
      "dmoral":8,
      "intervalSteps":20,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"flag",
      "title":"Закрасить украинский флаг",
      "dpain":-2,
      "dmoral":5,
      "intervalSteps":3,
      "timesLimit":8,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"center_music",
      "title":"Включить по центру патриотическую музыку",
      "dpain":10,
      "dmoral":5,
      "intervalSteps":15,
      "timesLimit":8,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"boyarishnik",
      "title":"Запустить в продажу настойку боярышника",
      "dpain":8,
      "dmoral":[  
         4,
         12,
         23
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":false,
      "enables":"",
      "disables":""
   },
   {  
      "id":"menyalo_out",
      "title":"Пустить слух об отставке Меняйло",
      "dpain":0,
      "dmoral":16,
      "intervalSteps":9,
      "timesLimit":6,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"turist",
      "title":"Объявить о скором прибытии бохатого туриста",
      "dpain":0,
      "dmoral":[  
         4,
         9,
         0,
         -2
      ],
      "intervalSteps":4,
      "timesLimit":25,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"olivier",
      "title":"Раздать оливье",
      "dpain":0,
      "dmoral":25,
      "intervalSteps":10,
      "timesLimit":15,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"fire_emergency_doctors",
      "title":"Уволить скорую помощь",
      "dpain":15,
      "dmoral":[  
         -15,
         -5,
         -1,
         -1
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"skameika",
      "title":"Покрасить скамейку",
      "dpain":-1,
      "dmoral":2,
      "intervalSteps":0,
      "timesLimit":50,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"peredel",
      "title":"Национализировать немножко имущества",
      "dpain":[  
         10,
         17,
         21
      ],
      "dmoral":35,
      "intervalSteps":9,
      "timesLimit":4,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"prodykt_tyrizm",
      "title":"Съездить в Украину за едой и лекарствами",
      "dpain":[  
         6,
         11
      ],
      "dmoral":[  
         15,
         2,
         -10
      ],
      "intervalSteps":5,
      "timesLimit":15,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"moleben",
      "title":"Провести молебен за процветание Крыма",
      "dpain":-8,
      "dmoral":22,
      "intervalSteps":5,
      "timesLimit":3,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"talony_to_new_ochered",
      "title":"Раздать талоны на новую очередь",
      "dpain":8,
      "dmoral":-5,
      "intervalSteps":2,
      "timesLimit":20,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"plati_na_vyhode",
      "title":"Разрешить платить в топике на выходе",
      "dpain":-8,
      "dmoral":16,
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"rushka_spec",
      "title":"Пригласить начальников из России",
      "dpain":9,
      "dmoral":[  
         10,
         17
      ],
      "intervalSteps":5,
      "timesLimit":6,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"ritual",
      "title":"Провести РИТУАЛ",
      "dpain":-5,
      "dmoral":15,
      "intervalSteps":7,
      "timesLimit":13,
      "alive":true,
      "enables":"mass_ban",
      "disables":""
   },
   {  
      "id":"mass_ban",
      "title":"Запретить массовые мероприятия",
      "dpain":25,
      "dmoral":-18,
      "intervalSteps":0,
      "timesLimit":1,
      "alive":false,
      "enables":"",
      "disables":"ritual"
   },
   {  
      "id":"sevntu_ne_plati",
      "title":"Не платить полгода преподавателям ВУЗа",
      "dpain":[  
         3,
         2,
         1,
         2,
         3
      ],
      "dmoral":[  
         -1,
         1,
         -2,
         2
      ],
      "intervalSteps":14,
      "timesLimit":2,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"ritual",
      "title":"Провести РИТУАЛ",
      "dpain":-5,
      "dmoral":15,
      "intervalSteps":7,
      "timesLimit":13,
      "alive":true,
      "enables":"mass_ban",
      "disables":""
   },
   {  
      "id":"portoviki",
      "title":"Уволить портовиков без зарплаты за неск мес",
      "dpain":[  
         5,
         4,
         3,
         2,
         1
      ],
      "dmoral":[  
         1,
         2,
         3,
         4,
         3
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"vzorvat_dom",
      "title":"Взорвать строящийся дом",
      "dpain":[  
         8,
         4,
         2
      ],
      "dmoral":[  
         -3,
         -2,
         -1
      ],
      "intervalSteps":15,
      "timesLimit":3,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"free_from_kredit",
      "title":"Разрешить не платить кредиты",
      "dpain":-19,
      "dmoral":[  
         4,
         12,
         12,
         18
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"gde_dengi_sooqa",
      "disables":""
   },
   {  
      "id":"hold_zarplata",
      "title":"Немножко задержать зарплату",
      "dpain":20,
      "dmoral":[  
         -10,
         -4.5,
         -2.1,
         -1.5,
         1.2
      ],
      "intervalSteps":12,
      "timesLimit":6,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"zimbabwe",
      "title":"Принять делегацию Зимбабве",
      "dpain":[  
         3,
         2,
         1
      ],
      "dmoral":[  
         6,
         4,
         2
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"onkolog",
      "title":"Развалить онкологический диспансер",
      "dpain":[  
         12,
         4,
         1
      ],
      "dmoral":[  
         -4,
         -2,
         -1
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"putin_liniya2",
      "title":"Вместо задать, разрешить посмотреть, как задают вопросы Путину",
      "dpain":29,
      "dmoral":[  
         -11,
         -4
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":false,
      "enables":"",
      "disables":""
   },
   {  
      "id":"hohly_zalili",
      "title":"Обвинить в бедах города хохлов",
      "dpain":-2,
      "dmoral":15,
      "intervalSteps":13,
      "timesLimit":14,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"inbum_mgi",
      "title":"Раздеребанить морские институты",
      "dpain":[  
         15,
         12,
         9,
         3,
         1
      ],
      "dmoral":[  
         -3,
         -6,
         -8
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"abamka_zalil",
      "title":"Обвинить в бедах города Абаму-абизяну",
      "dpain":-3,
      "dmoral":11,
      "intervalSteps":18,
      "timesLimit":13,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"bridge",
      "title":"Объявить о начале строительства моста",
      "dpain":0,
      "dmoral":15,
      "intervalSteps":30,
      "timesLimit":15,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"dat_vody",
      "title":"Включить воду на 3 часа в день",
      "dpain":[  
         -3,
         -2,
         -1
      ],
      "dmoral":[  
         13,
         8,
         5,
         1
      ],
      "intervalSteps":10,
      "timesLimit":4,
      "alive":false,
      "enables":"",
      "disables":""
   },
   {  
      "id":"vinco",
      "title":"Запретить продажу домашнего вина",
      "dpain":25,
      "dmoral":[  
         -5,
         -8,
         -13,
         -20
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"boyarishnik",
      "disables":""
   },
   {  
      "id":"gde_dengi_sooqa",
      "title":"Запустить российских коллекторов",
      "dpain":28,
      "dmoral":[  
         -15,
         -10,
         -4
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":false,
      "enables":"",
      "disables":""
   },
   {  
      "id":"letter_to_pitun",
      "title":"Написать письмо Путину",
      "dpain":0,
      "dmoral":1,
      "intervalSteps":10,
      "timesLimit":5,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"lavrov",
      "title":"Дать пососать пиндосам",
      "dpain":[  
         -10,
         -7,
         -3,
         -2,
         -0.5
      ],
      "dmoral":[  
         1,
         2,
         3,
         5,
         8,
         13
      ],
      "intervalSteps":25,
      "timesLimit":3,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"navoz",
      "title":"Удобрить клумбы в центре свежим говном",
      "dpain":5,
      "dmoral":-5,
      "intervalSteps":5,
      "timesLimit":4,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"veterany_bolnica",
      "title":"Выгнать из больницы ветеранов ради молодежной конф",
      "dpain":[  
         7,
         4,
         1
      ],
      "dmoral":[  
         -1,
         2,
         3
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"invite_bratushki",
      "title":"Пригласить братушек с Донбасса",
      "dpain":14,
      "dmoral":10,
      "intervalSteps":4,
      "timesLimit":8,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"Beach",
      "title":"Закрыть доступ на пляж",
      "dpain":15,
      "dmoral":-10,
      "intervalSteps":10,
      "timesLimit":5,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"pravoseki_shron",
      "title":"Обнаружить схрон \"Правого Сектора\"",
      "dpain":[  
         -2,
         -2,
         -1
      ],
      "dmoral":[  
         9,
         3
      ],
      "intervalSteps":17,
      "timesLimit":9,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"35bat",
      "title":"Почтить дидов на 35 батарее",
      "dpain":[  
         -7,
         -3,
         -1
      ],
      "dmoral":16,
      "intervalSteps":10,
      "timesLimit":4,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"putin_liniya",
      "title":"Разрешить задать вопрос Путину",
      "dpain":-15,
      "dmoral":[  
         8,
         11,
         14
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"putin_liniya2",
      "disables":""
   },
   {  
      "id":"voenkomat",
      "title":"Объявить приписку в военкомат (все в очередь)",
      "dpain":[  
         1,
         3,
         5,
         8,
         12,
         15
      ],
      "dmoral":[  
         -3,
         -2,
         -1
      ],
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"remont_vody",
      "title":"Ремонт водопровода в течение 5 мес",
      "dpain":[  
         1,
         3,
         5,
         7,
         11,
         15
      ],
      "dmoral":[  
         -1,
         -2,
         -3,
         -4,
         -6,
         -9
      ],
      "intervalSteps":30,
      "timesLimit":2,
      "alive":true,
      "enables":"remont_vody",
      "disables":""
   },
   {  
      "id":"fzv_poterya",
      "title":"Потерять документы обратившихся в ФЗВ",
      "dpain":[  
         17
      ],
      "dmoral":-5,
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"sevteploenergo_schet",
      "title":"Выслать левые счета от \"Севтеплоэнерго\"",
      "dpain":7,
      "dmoral":-5,
      "intervalSteps":3,
      "timesLimit":30,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"oduvan",
      "title":"Повалить скульпутуру \"Одуванчик\"",
      "dpain":0,
      "dmoral":12,
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"poezd_druzby",
      "title":"Организовать оборону от \"поезда дружбы\"",
      "dpain":0,
      "dmoral":[  
         5,
         4,
         3,
         6,
         2
      ],
      "intervalSteps":13,
      "timesLimit":4,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"rubli_dolary",
      "title":"Обменять все доллары на рубли, чтоб пиндосы соснули",
      "dpain":0,
      "dmoral":7,
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"u_hohlov",
      "title":"Рассказать по телеку чё там у хохлов",
      "dpain":10,
      "dmoral":10,
      "intervalSteps":15,
      "timesLimit":5,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"mass_ban",
      "title":"Запретить массовые мероприятия",
      "dpain":25,
      "dmoral":-18,
      "intervalSteps":0,
      "timesLimit":1,
      "alive":false,
      "enables":"",
      "disables":"ritual"
   },
   {  
      "id":"zkh_tarif",
      "title":"Повысить тарифы ЖКХ",
      "dpain":35,
      "dmoral":-20,
      "intervalSteps":15,
      "timesLimit":2,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"dorogi",
      "title":"Установить блокпосты против биндер",
      "dpain":-5,
      "dmoral":3,
      "intervalSteps":6,
      "timesLimit":4,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"Visa_MC_PayPal",
      "title":"Отключить Visa/MC/Pay Pal",
      "dpain":5,
      "dmoral":-3,
      "intervalSteps":0,
      "timesLimit":1,
      "alive":true,
      "enables":"",
      "disables":""
   },
   {  
      "id":"bindera-search",
      "title":"Искать биндеровца",
      "dpain":-10,
      "dmoral":10,
      "intervalSteps":15,
      "timesLimit":2,
      "alive":true,
      "enables":"",
      "disables":""
   }
]
